export { default as Farfetch } from './Farfetch';
export { default as BEES } from './BEES';
export { default as DezINove } from './DezINove';
export { default as Superlogica } from './Superlogica';
export { default as Venturus } from './Venturus';
export { default as Heineken } from './Heineken';
export { default as SuperiorIndustries } from './SuperiorIndustries';
export { default as SIICUSP } from './SIICUSP';
export { default as IFMS } from './IFMS';
